// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noderequest.proto

package com.ytfs.service.packet;

public final class UploadShardRequest {
  private UploadShardRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UploadShardRequestBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.UploadShardRequestBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 BPDID = 1;</code>
     */
    boolean hasBPDID();
    /**
     * <code>required int32 BPDID = 1;</code>
     */
    int getBPDID();

    /**
     * <code>required int64 VBI = 2;</code>
     */
    boolean hasVBI();
    /**
     * <code>required int64 VBI = 2;</code>
     */
    long getVBI();

    /**
     * <code>required bytes BPDSIGN = 3;</code>
     */
    boolean hasBPDSIGN();
    /**
     * <code>required bytes BPDSIGN = 3;</code>
     */
    com.google.protobuf.ByteString getBPDSIGN();

    /**
     * <code>required bytes DAT = 4;</code>
     */
    boolean hasDAT();
    /**
     * <code>required bytes DAT = 4;</code>
     */
    com.google.protobuf.ByteString getDAT();

    /**
     * <code>required bytes VHF = 5;</code>
     */
    boolean hasVHF();
    /**
     * <code>required bytes VHF = 5;</code>
     */
    com.google.protobuf.ByteString getVHF();

    /**
     * <code>required bytes USERSIGN = 6;</code>
     */
    boolean hasUSERSIGN();
    /**
     * <code>required bytes USERSIGN = 6;</code>
     */
    com.google.protobuf.ByteString getUSERSIGN();
  }
  /**
   * Protobuf type {@code protobuf.UploadShardRequestBuf}
   */
  public  static final class UploadShardRequestBuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.UploadShardRequestBuf)
      UploadShardRequestBufOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadShardRequestBuf.newBuilder() to construct.
    private UploadShardRequestBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadShardRequestBuf() {
      bPDID_ = 0;
      vBI_ = 0L;
      bPDSIGN_ = com.google.protobuf.ByteString.EMPTY;
      dAT_ = com.google.protobuf.ByteString.EMPTY;
      vHF_ = com.google.protobuf.ByteString.EMPTY;
      uSERSIGN_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadShardRequestBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bPDID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              vBI_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bPDSIGN_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dAT_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              vHF_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              uSERSIGN_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ytfs.service.packet.UploadShardRequest.internal_static_protobuf_UploadShardRequestBuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ytfs.service.packet.UploadShardRequest.internal_static_protobuf_UploadShardRequestBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf.class, com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf.Builder.class);
    }

    private int bitField0_;
    public static final int BPDID_FIELD_NUMBER = 1;
    private int bPDID_;
    /**
     * <code>required int32 BPDID = 1;</code>
     */
    public boolean hasBPDID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 BPDID = 1;</code>
     */
    public int getBPDID() {
      return bPDID_;
    }

    public static final int VBI_FIELD_NUMBER = 2;
    private long vBI_;
    /**
     * <code>required int64 VBI = 2;</code>
     */
    public boolean hasVBI() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 VBI = 2;</code>
     */
    public long getVBI() {
      return vBI_;
    }

    public static final int BPDSIGN_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bPDSIGN_;
    /**
     * <code>required bytes BPDSIGN = 3;</code>
     */
    public boolean hasBPDSIGN() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes BPDSIGN = 3;</code>
     */
    public com.google.protobuf.ByteString getBPDSIGN() {
      return bPDSIGN_;
    }

    public static final int DAT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString dAT_;
    /**
     * <code>required bytes DAT = 4;</code>
     */
    public boolean hasDAT() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes DAT = 4;</code>
     */
    public com.google.protobuf.ByteString getDAT() {
      return dAT_;
    }

    public static final int VHF_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString vHF_;
    /**
     * <code>required bytes VHF = 5;</code>
     */
    public boolean hasVHF() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes VHF = 5;</code>
     */
    public com.google.protobuf.ByteString getVHF() {
      return vHF_;
    }

    public static final int USERSIGN_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString uSERSIGN_;
    /**
     * <code>required bytes USERSIGN = 6;</code>
     */
    public boolean hasUSERSIGN() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes USERSIGN = 6;</code>
     */
    public com.google.protobuf.ByteString getUSERSIGN() {
      return uSERSIGN_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBPDID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVBI()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBPDSIGN()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDAT()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVHF()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUSERSIGN()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bPDID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, vBI_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, bPDSIGN_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, dAT_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, vHF_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, uSERSIGN_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bPDID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, vBI_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bPDSIGN_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, dAT_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, vHF_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, uSERSIGN_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf)) {
        return super.equals(obj);
      }
      com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf other = (com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf) obj;

      boolean result = true;
      result = result && (hasBPDID() == other.hasBPDID());
      if (hasBPDID()) {
        result = result && (getBPDID()
            == other.getBPDID());
      }
      result = result && (hasVBI() == other.hasVBI());
      if (hasVBI()) {
        result = result && (getVBI()
            == other.getVBI());
      }
      result = result && (hasBPDSIGN() == other.hasBPDSIGN());
      if (hasBPDSIGN()) {
        result = result && getBPDSIGN()
            .equals(other.getBPDSIGN());
      }
      result = result && (hasDAT() == other.hasDAT());
      if (hasDAT()) {
        result = result && getDAT()
            .equals(other.getDAT());
      }
      result = result && (hasVHF() == other.hasVHF());
      if (hasVHF()) {
        result = result && getVHF()
            .equals(other.getVHF());
      }
      result = result && (hasUSERSIGN() == other.hasUSERSIGN());
      if (hasUSERSIGN()) {
        result = result && getUSERSIGN()
            .equals(other.getUSERSIGN());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBPDID()) {
        hash = (37 * hash) + BPDID_FIELD_NUMBER;
        hash = (53 * hash) + getBPDID();
      }
      if (hasVBI()) {
        hash = (37 * hash) + VBI_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVBI());
      }
      if (hasBPDSIGN()) {
        hash = (37 * hash) + BPDSIGN_FIELD_NUMBER;
        hash = (53 * hash) + getBPDSIGN().hashCode();
      }
      if (hasDAT()) {
        hash = (37 * hash) + DAT_FIELD_NUMBER;
        hash = (53 * hash) + getDAT().hashCode();
      }
      if (hasVHF()) {
        hash = (37 * hash) + VHF_FIELD_NUMBER;
        hash = (53 * hash) + getVHF().hashCode();
      }
      if (hasUSERSIGN()) {
        hash = (37 * hash) + USERSIGN_FIELD_NUMBER;
        hash = (53 * hash) + getUSERSIGN().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.UploadShardRequestBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.UploadShardRequestBuf)
        com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ytfs.service.packet.UploadShardRequest.internal_static_protobuf_UploadShardRequestBuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ytfs.service.packet.UploadShardRequest.internal_static_protobuf_UploadShardRequestBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf.class, com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf.Builder.class);
      }

      // Construct using com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bPDID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        vBI_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        bPDSIGN_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        dAT_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        vHF_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        uSERSIGN_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ytfs.service.packet.UploadShardRequest.internal_static_protobuf_UploadShardRequestBuf_descriptor;
      }

      public com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf getDefaultInstanceForType() {
        return com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf.getDefaultInstance();
      }

      public com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf build() {
        com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf buildPartial() {
        com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf result = new com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bPDID_ = bPDID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vBI_ = vBI_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bPDSIGN_ = bPDSIGN_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dAT_ = dAT_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.vHF_ = vHF_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uSERSIGN_ = uSERSIGN_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf) {
          return mergeFrom((com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf other) {
        if (other == com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf.getDefaultInstance()) return this;
        if (other.hasBPDID()) {
          setBPDID(other.getBPDID());
        }
        if (other.hasVBI()) {
          setVBI(other.getVBI());
        }
        if (other.hasBPDSIGN()) {
          setBPDSIGN(other.getBPDSIGN());
        }
        if (other.hasDAT()) {
          setDAT(other.getDAT());
        }
        if (other.hasVHF()) {
          setVHF(other.getVHF());
        }
        if (other.hasUSERSIGN()) {
          setUSERSIGN(other.getUSERSIGN());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBPDID()) {
          return false;
        }
        if (!hasVBI()) {
          return false;
        }
        if (!hasBPDSIGN()) {
          return false;
        }
        if (!hasDAT()) {
          return false;
        }
        if (!hasVHF()) {
          return false;
        }
        if (!hasUSERSIGN()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bPDID_ ;
      /**
       * <code>required int32 BPDID = 1;</code>
       */
      public boolean hasBPDID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 BPDID = 1;</code>
       */
      public int getBPDID() {
        return bPDID_;
      }
      /**
       * <code>required int32 BPDID = 1;</code>
       */
      public Builder setBPDID(int value) {
        bitField0_ |= 0x00000001;
        bPDID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 BPDID = 1;</code>
       */
      public Builder clearBPDID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bPDID_ = 0;
        onChanged();
        return this;
      }

      private long vBI_ ;
      /**
       * <code>required int64 VBI = 2;</code>
       */
      public boolean hasVBI() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 VBI = 2;</code>
       */
      public long getVBI() {
        return vBI_;
      }
      /**
       * <code>required int64 VBI = 2;</code>
       */
      public Builder setVBI(long value) {
        bitField0_ |= 0x00000002;
        vBI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 VBI = 2;</code>
       */
      public Builder clearVBI() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vBI_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bPDSIGN_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes BPDSIGN = 3;</code>
       */
      public boolean hasBPDSIGN() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes BPDSIGN = 3;</code>
       */
      public com.google.protobuf.ByteString getBPDSIGN() {
        return bPDSIGN_;
      }
      /**
       * <code>required bytes BPDSIGN = 3;</code>
       */
      public Builder setBPDSIGN(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bPDSIGN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes BPDSIGN = 3;</code>
       */
      public Builder clearBPDSIGN() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bPDSIGN_ = getDefaultInstance().getBPDSIGN();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dAT_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes DAT = 4;</code>
       */
      public boolean hasDAT() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes DAT = 4;</code>
       */
      public com.google.protobuf.ByteString getDAT() {
        return dAT_;
      }
      /**
       * <code>required bytes DAT = 4;</code>
       */
      public Builder setDAT(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dAT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes DAT = 4;</code>
       */
      public Builder clearDAT() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dAT_ = getDefaultInstance().getDAT();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString vHF_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes VHF = 5;</code>
       */
      public boolean hasVHF() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes VHF = 5;</code>
       */
      public com.google.protobuf.ByteString getVHF() {
        return vHF_;
      }
      /**
       * <code>required bytes VHF = 5;</code>
       */
      public Builder setVHF(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        vHF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes VHF = 5;</code>
       */
      public Builder clearVHF() {
        bitField0_ = (bitField0_ & ~0x00000010);
        vHF_ = getDefaultInstance().getVHF();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString uSERSIGN_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes USERSIGN = 6;</code>
       */
      public boolean hasUSERSIGN() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes USERSIGN = 6;</code>
       */
      public com.google.protobuf.ByteString getUSERSIGN() {
        return uSERSIGN_;
      }
      /**
       * <code>required bytes USERSIGN = 6;</code>
       */
      public Builder setUSERSIGN(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        uSERSIGN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes USERSIGN = 6;</code>
       */
      public Builder clearUSERSIGN() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uSERSIGN_ = getDefaultInstance().getUSERSIGN();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.UploadShardRequestBuf)
    }

    // @@protoc_insertion_point(class_scope:protobuf.UploadShardRequestBuf)
    private static final com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf();
    }

    public static com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UploadShardRequestBuf>
        PARSER = new com.google.protobuf.AbstractParser<UploadShardRequestBuf>() {
      public UploadShardRequestBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadShardRequestBuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadShardRequestBuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadShardRequestBuf> getParserForType() {
      return PARSER;
    }

    public com.ytfs.service.packet.UploadShardRequest.UploadShardRequestBuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_UploadShardRequestBuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_UploadShardRequestBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021noderequest.proto\022\010protobuf\"p\n\025UploadS" +
      "hardRequestBuf\022\r\n\005BPDID\030\001 \002(\005\022\013\n\003VBI\030\002 \002" +
      "(\003\022\017\n\007BPDSIGN\030\003 \002(\014\022\013\n\003DAT\030\004 \002(\014\022\013\n\003VHF\030" +
      "\005 \002(\014\022\020\n\010USERSIGN\030\006 \002(\014B-\n\027com.ytfs.serv" +
      "ice.packetB\022UploadShardRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_UploadShardRequestBuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_UploadShardRequestBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_UploadShardRequestBuf_descriptor,
        new java.lang.String[] { "BPDID", "VBI", "BPDSIGN", "DAT", "VHF", "USERSIGN", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
